import { defineConfig } from 'astro/config';
import tailwind from '@astrojs/tailwind';
import vercel from '@astrojs/vercel/static';

export default defineConfig({
  site: 'https://rumroom.world',
  // trailingSlash removed — was causing redirect loop on Vercel
  integrations: [
    tailwind(),
    // sitemap temporarily removed due to incompatibility with Astro 4 + endpoint routes.
    // Custom sitemap is generated by src/pages/sitemap.xml.ts
  ],
  output: 'static',
  adapter: vercel(),

  // Старые слаги, на которые у Google остались ссылки (GSC: Not found 404).
  // Держим редиректы, чтобы не терять уже накопленные сигналы.
  redirects: {
    '/bali/bali-visa-guide': '/bali/visa-guide/',
    '/bali/bali-visa-guide/': '/bali/visa-guide/',
    '/bali/bali-for-first-timers': '/bali/for-first-timers/',
    '/bali/bali-for-first-timers/': '/bali/for-first-timers/',
  },
});
