import { defineConfig } from 'astro/config';
import tailwind from '@astrojs/tailwind';
import vercel from '@astrojs/vercel/static';

export default defineConfig({
  site: 'https://rumroom.world',
  // trailingSlash removed — was causing redirect loop on Vercel
  integrations: [
    tailwind(),
    // sitemap temporarily removed due to incompatibility with Astro 4 + endpoint routes.
    // Custom sitemap is generated by src/pages/sitemap.xml.ts
  ],
  output: 'static',
  adapter: vercel(),
});
